---
abstract: 'Log all DBI queries'
author:
  - 'Jacob Gelbman <gelbman@gmail.com>'
build_requires:
  DBD::SQLite: '0'
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBI-Log
no_index:
  directory:
    - t
    - inc
requires:
  DBI: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.014'
